export const heroInfos = [
  {
    groupId: '1',
    name: '김현진',
    title: '휴지맨',
    description: '저는 휴지를 주워서 학교가 깨끗해지는걸 좋아해요!',
    code: '1234',
    profileImage: '/images/hero2.png',
  },
  {
    groupId: '1',
    name: '김현진',
    title: '휴지맨',
    description: '저는 휴지를 주워서 학교가 깨끗해지는걸 좋아해요!',
    code: '1234',
    profileImage: '/images/hero2.png',
  },
  {
    groupId: '1',
    name: '김현진',
    title: '휴지맨',
    description: '저는 휴지를 주워서 학교가 깨끗해지는걸 좋아해요!',
    code: '1234',
    profileImage: '/images/hero2.png',
  },
  {
    groupId: '1',
    name: '김현진',
    title: '휴지맨',
    description: '저는 휴지를 주워서 학교가 깨끗해지는걸 좋아해요!',
    code: '1234',
    profileImage: '/images/hero2.png',
  },
  {
    groupId: '1',
    name: '김현진',
    title: '휴지맨',
    description: '저는 휴지를 주워서 학교가 깨끗해지는걸 좋아해요!',
    code: '1234',
    profileImage: '/images/hero2.png',
  },
  {
    groupId: '1',
    name: '김현진',
    title: '휴지맨',
    description: '저는 휴지를 주워서 학교가 깨끗해지는걸 좋아해요!',
    code: '1234',
    profileImage: '/images/hero2.png',
  },
  {
    groupId: '1',
    name: '김현진',
    title: '휴지맨',
    description: '저는 휴지를 주워서 학교가 깨끗해지는걸 좋아해요!',
    code: '1234',
    profileImage: '/images/hero2.png',
  },
  {
    groupId: '1',
    name: '김현진',
    title: '휴지맨',
    description: '저는 휴지를 주워서 학교가 깨끗해지는걸 좋아해요!',
    code: '1234',
    profileImage: '/images/hero2.png',
  },
  {
    groupId: '1',
    name: '김현진',
    title: '휴지맨',
    description: '저는 휴지를 주워서 학교가 깨끗해지는걸 좋아해요!',
    code: '1234',
    profileImage: '/images/hero2.png',
  },
  {
    groupId: '1',
    name: '김현진',
    title: '휴지맨',
    description: '저는 휴지를 주워서 학교가 깨끗해지는걸 좋아해요!',
    code: '1234',
    profileImage: '/images/hero2.png',
  },
  {
    groupId: '1',
    name: '김현진',
    title: '휴지맨',
    description: '저는 휴지를 주워서 학교가 깨끗해지는걸 좋아해요!',
    code: '1234',
    profileImage: '/images/hero2.png',
  },
  {
    groupId: '1',
    name: '김현진',
    title: '휴지맨',
    description: '저는 휴지를 주워서 학교가 깨끗해지는걸 좋아해요!',
    code: '1234',
    profileImage: '/images/hero2.png',
  },
  {
    groupId: '1',
    name: '김현진',
    title: '휴지맨',
    description: '저는 휴지를 주워서 학교가 깨끗해지는걸 좋아해요!',
    code: '1234',
    profileImage: '/images/hero2.png',
  },
  {
    groupId: '1',
    name: '김현진',
    title: '휴지맨',
    description: '저는 휴지를 주워서 학교가 깨끗해지는걸 좋아해요!',
    code: '1234',
    profileImage: '/images/hero2.png',
  },
  {
    groupId: '1',
    name: '김현진',
    title: '휴지맨',
    description: '저는 휴지를 주워서 학교가 깨끗해지는걸 좋아해요!',
    code: '1234',
    profileImage: '/images/hero2.png',
  },
  {
    groupId: '1',
    name: '김현진',
    title: '휴지맨',
    description: '저는 휴지를 주워서 학교가 깨끗해지는걸 좋아해요!',
    code: '1234',
    profileImage: '/images/hero2.png',
  },
  {
    groupId: '1',
    name: '김현진',
    title: '휴지맨',
    description: '저는 휴지를 주워서 학교가 깨끗해지는걸 좋아해요!',
    code: '1234',
    profileImage: '/images/hero2.png',
  },
  {
    groupId: '1',
    name: '김현진',
    title: '휴지맨',
    description: '저는 휴지를 주워서 학교가 깨끗해지는걸 좋아해요!',
    code: '1234',
    profileImage: '/images/hero2.png',
  },
  {
    groupId: '1',
    name: '김현진',
    title: '휴지맨',
    description: '저는 휴지를 주워서 학교가 깨끗해지는걸 좋아해요!',
    code: '1234',
    profileImage: '/images/hero2.png',
  },
];
